Yith Conflict - Add to wishlist button does not show up for vendor roles. #707
wcvendors/wcvendors pull request #708
Opened 2020-11-09 13:49 UTC by mahlamusa

### All Submissions:

* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #707 .

### How to test the changes in this Pull Request:

1.  Log in as a customer/another role
2. Check a single product page and see the "Add to wishlist" Button
3. The 'Add to wishlist" button must be visible when logged in as Customer/Vendor/Administrator or any other role.
4. If the product is already on the wishlist, the appropriate message must be visible when logged in as Customer/Vendor/Administrator or any other role

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2020-11-10 04:54 UTC, ketulsheth85 commented on classes/admin/class-admin-users.php
> -		echo '<style>';
By removing this all the advanced stylesheets are removed.

2020-11-10 04:55 UTC, ketulsheth85 requested changes
By removing this all the advanced stylesheets are removed.

2020-11-10 05:07 UTC, digitalchild reviewed
Move the styles into its own wp_enqueue_style call.

2020-11-16 06:55 UTC, digitalchild approved these changes

2020-11-17 11:42 UTC, ketulsheth85 approved these changes

2020-11-17 11:48 UTC, merged