Fixed: Order total incorrect in vendor order emails when coupon is used #726
wcvendors/wcvendors pull request #727
Opened 2021-01-18 12:57 UTC by ketulsheth85

### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes #726 .

### How to test the changes in this Pull Request:

1.) create a vendor coupon
2.) Use it for an order
3.) see the product total

2021-01-19 02:42 UTC, digitalchild reviewed
We have options in the email that allows the marketplace admin to show the totals display with the commission or product, or both commission and product or no totals. We need to ensure that this is still being output as we have a lot of marketplaces that only show the commission totals or the product totals.

2021-01-28 08:06 UTC, digitalchild requested changes
The values are not changing in the email contents with these changes.

2021-01-28 08:06 UTC, digitalchild commented on classes/includes/wcv-template-functions.php
> +		$discount 			 = $order->get_total_discount();
This would get the total discounts from all vendors, not the particular vendor. resulting in the amounts not being correct. Need to check what the coupon was, who owns it and then determine the coupon discount amount.

2021-02-19 06:51 UTC, mahlamusa approved these changes

2021-02-20 05:41 UTC, digitalchild approved these changes

2021-02-20 05:41 UTC, merged