Updated: enhancement for New customer order vendor notification - Add link in the order number redirecting to /pro-dashboard/orders page #729
wcvendors/wcvendors pull request #730
Opened 2021-01-21 11:51 UTC by ketulsheth85

### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes #729 .

### How to test the changes in this Pull Request:

1. Check the pro plugin is enabled.
2. Put an order with the vendor product.
2. As admin user mark that order as processing.
3. Check vendor email order number has the link to the pro dashboard.

2021-01-22 09:52 UTC, digitalchild reviewed
Could we add an action here instead of that we could hook into within pro? thus not having to need to do a class detect here?

2021-01-25 10:54 UTC, digitalchild requested changes
Add an action here instead of a filter.

2021-01-25 10:54 UTC, digitalchild commented on templates/emails/vendor-order-details.php
> +	$order_before_after = apply_filters( 'wcvendors_order_number_link_in_email_template', $before, $after );
Emails use actions for hooking into various aspects not a filter. If we had a simple do_action here we could move all of that logic into the pro code.

2021-02-02 10:28 UTC, ketulsheth85 commented on templates/emails/vendor-order-details.php
> +	$order_before_after = apply_filters( 'wcvendors_order_number_link_in_email_template', $before, $after );
If we move full Order Id to the pro by do_action then those who don't have the pro plugin that time in their email template this Order Id will be not appended.

2021-02-03 04:38 UTC, digitalchild approved these changes

2021-02-03 04:38 UTC, merged