New Admin Vendor Manager Page
wcvendors/wcvendors pull request #753
Opened 2021-04-20 15:56 UTC by Mrlunsuper

### All Submissions:

* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2021-04-22 08:44 UTC, digitalchild requested changes
Please see comments below

2021-04-22 21:02 UTC, mahlamusa requested changes
Please see comments.

- There are multiple uses of incorrect and inconsistent text domain: replace wcv-vendor, wc-vendor with the correct text domain `wc-vendors`
- Avoid concatinating variables into strings, use 'sprintf' function and placeholders instead
- The delete row action does not work
- The toggle button does not work. When you enable/approve a vendor and reload the page, the switch must be on for enabled vendors

2021-04-23 11:12 UTC, mahlamusa requested changes

2021-04-23 11:12 UTC, mahlamusa commented on src/Admin/Assets.php
> +		wp_register_style('wcv_vendors_style',WCV_PLUGIN_URL.'assets/src/scss/vendors-css.css');
Enqueue styles from `WCV_PLUGIN_URL . 'assets/css/vendors-css.css`, the src folder is for development only.

Use the build tools to build the css int the `assets/css` and enqueue from there.

2021-04-23 11:12 UTC, mahlamusa commented on src/Admin/Assets.php
> +			wp_register_script( 'wcv_vendor-edit', WCV_PLUGIN_URL . 'assets/src/js/admin/vendor-edit.js', array( 'jquery' ), WCV_VERSION, true );
use scripts from assets/js folder, src folder is for development only

2021-04-23 11:12 UTC, mahlamusa commented on src/Admin/Menus.php
> +			'label'   => __('Vendors','wc-vendor'),
I still see instances of 'wc-vendor' as text domain, it should be 'wc-vendors'

2021-04-23 11:26 UTC, mahlamusa commented
The toggle to enable a vendor is still not working, I think this is because the ajaxurl is localized as ajax_url and it must be used like so:
```$.ajax({
	method: 'POST',
	url: wcv_ajax_obj.ajax_url,
	...```

Also the row actions in the table are still not firing.

2021-04-23 17:04 UTC, Mrlunsuper commented on src/Admin/Menus.php
> +			'label'   => __('Vendors','wc-vendor'),
Change text domain to wc-vendors

2021-04-23 17:10 UTC, Mrlunsuper commented on src/Admin/Assets.php
> +			wp_register_script( 'wcv_vendor-edit', WCV_PLUGIN_URL . 'assets/src/js/admin/vendor-edit.js', array( 'jquery' ), WCV_VERSION, true );
add css and js folder and change page slug

2021-04-23 17:11 UTC, Mrlunsuper commented on src/Admin/Assets.php
> +		wp_register_style('wcv_vendors_style',WCV_PLUGIN_URL.'assets/src/scss/vendors-css.css');
added css folder and build css file from scss file

2021-05-18 02:55 UTC, digitalchild requested changes
The code formatting does not look to be to WordPress standards, please ensure that you're using the PHPCS WordPress sniffs when submitting code.

2021-05-22 14:54 UTC, mahlamusa approved these changes

2021-12-02 07:55 UTC, digitalchild requested changes
Looks good. The only thing is the Approve / Deny row actions should only show for pending vendors.

2021-12-08 06:58 UTC, digitalchild approved these changes

2021-12-08 09:27 UTC, merged