Add: Delete commission row
wcvendors/wcvendors pull request #765
Opened 2021-06-08 06:27 UTC by Mrlunsuper

### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #762 .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x ] Have you successfully run tests with your changes locally?

2021-06-09 05:46 UTC, digitalchild requested changes
When deleting a commission on pages other than page one the page should be redirected back to the same page the user was on. 

Example: Deleting a commission on page 3 of commissions should go back to this page after deleting. 

Notes: This does work as expected for the bulk action delete.

2021-06-09 05:52 UTC, digitalchild commented
Tests required for this feature.

2021-06-10 12:51 UTC, ketulsheth85 approved these changes

2021-06-15 05:14 UTC, digitalchild approved these changes

2021-06-15 05:15 UTC, merged