Prepare version 2.3.0 #774
wcvendors/wcvendors pull request #775
Opened 2021-07-06 05:18 UTC by Mrlunsuper

### Changes proposed in this Pull Request:
Version 2.3.0 ready for release.

2021-07-07 11:55 UTC, ketulsheth85 approved these changes

2021-07-12 03:34 UTC, digitalchild requested changes
See my comments. You will need to update the readme.txt to ensure the tested versions are the latest betas.

2021-07-12 03:34 UTC, digitalchild commented on class-wc-vendors.php
> + * Tested up to:         5.7.2
We need to test with the soon to be released WP5.8 as this is now in beta

2021-07-12 03:34 UTC, digitalchild commented on class-wc-vendors.php
> + * WC tested up to:      5.4.1
WooCommerce 5.5.0 is scheduled to be released tomorrow. We should be doing all of our testings with the latest beta's as well as the latest final releases.

2021-07-12 03:34 UTC, digitalchild commented on changelog.txt
> +Verison 2.3.0 - 6th July 2021
Update this date to the 14th of July as it will take us at least till the end of tomorrow to finish testing.

2021-07-15 07:10 UTC, digitalchild approved these changes

2021-07-15 09:03 UTC, bdesai1982 approved these changes

2021-07-16 05:26 UTC, merged