Update sales report to compatibility with refund update
wcvendors/wcvendors pull request #822
Opened 2022-01-24 09:21 UTC by Mrlunsuper

### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Updated: View order screen in sales report table in Vendor Dashboard
- Updated: Orders table view items in Vendor Dashboard

### How to test the changes in this Pull Request:

1. Login as vendor account
2. Go to Vendor Dashboard
3. Click Show Orders in the Sales Report table will see refund detail if the order has been refunded
4. Click View items in the Orders table will see refund detail if the order has been refunded

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2022-01-28 05:14 UTC, digitalchild requested changes
Move the setting from Pro into marketplace and remove the Pro requirement.

2022-01-29 08:02 UTC, digitalchild requested changes
The qty isn't showing on the order for what product is refunded. For the No Tax, we should leave that out for now. 
![Vendor_Dashboard_–_WC_Vendors](https://user-images.githubusercontent.com/909468/151653040-d74daa2e-3bdb-482e-862e-b8066fb6a343.jpg)

2022-01-29 08:02 UTC, digitalchild commented on templates/dashboard/orders.php
> +						<br/><strong><?php echo esc_html__( 'Refuned:', 'wc-vendors' ); ?></strong>
refunded is misspelled.

2022-02-07 02:19 UTC, Mrlunsuper commented
> The qty isn't showing on the order for what product is refunded. For the No Tax, we should leave that out for now. ![Vendor_Dashboard_–_WC_Vendors](https://user-images.githubusercontent.com/909468/151653040-d74daa2e-3bdb-482e-862e-b8066fb6a343.jpg)

Can you show me the order details and product details?

2022-02-07 03:45 UTC, digitalchild commented
Order details here. 
![Edit_order_“Order_–_July_29__2021___05_21_AM”_‹_WC_Vendors_—_WordPress](https://user-images.githubusercontent.com/909468/152721277-b7dad420-52e4-405e-9662-93b79fc0df19.jpg)

2022-02-07 03:51 UTC, digitalchild commented
Refund line should read as follows: 

**Refunded:** 1x Price - Product Name

2022-02-07 05:42 UTC, bdesai1982 commented
Steps to execute:
1. Customer places an order for multiple products in a single order 
2. Admin initiates a refund for any one product
3. The status in the commission's table is updated from due --> reversed only for the vendor but not for the admin
4. But the status is updated for both the admin and the vendor when the entire order is placed for a refund.
![Screenshot_15](https://user-images.githubusercontent.com/77658351/152730505-083e1b90-dd02-43c1-96f9-88f4255e362c.png)

![Screenshot_16](https://user-images.githubusercontent.com/77658351/152730863-8a413ca5-6638-44da-8a4e-2df42329de5a.png)

2022-02-11 07:14 UTC, digitalchild requested changes
The qty on the orders display is still showing 0. 
![Vendor_Dashboard_–_WC_Vendors](https://user-images.githubusercontent.com/909468/153551090-f196db33-099b-41ba-9b3f-0309e39959d9.jpg)

2022-03-03 04:28 UTC, digitalchild approved these changes

2022-03-03 04:28 UTC, merged