Updated: Vendors list page
wcvendors/wcvendors pull request #846
Opened 2022-05-05 07:21 UTC by Mrlunsuper

### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #845.
- Redesign vendors list with two display mode and responsive
- Added option to select default avatar source and display mode `WC Vendors -> Settings -> Display`
- Added vendor search bar
- Show more vendor information

### How to test the changes in this Pull Request:

1. Go to vendors page
2. Try to search and change display mode

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2022-05-06 04:02 UTC, digitalchild requested changes
This is looking great, see my few comments for updates.

2022-05-06 04:02 UTC, digitalchild commented on classes/admin/settings/class-wcv-settings-display.php
> +						array(
We should use the avatar options available in WordPress > Settings > Discussion to give greater flexibility for avatar displays.

2022-05-31 08:31 UTC, mahlamusa approved these changes

2022-06-10 10:21 UTC, ketulsheth85 approved these changes

2022-06-10 10:53 UTC, ketulsheth85 commented on templates/front/vendor-list-loop.php
> +		<?php echo $avatar; ?>
<a href="<?php echo esc_url( $shop_link ); ?>"><?php echo $avatar; ?></a>

Add hyperlink to the image

2022-06-10 10:53 UTC, ketulsheth85 commented on templates/front/vendor-list-loop.php
> +		<h3 class="vendor_list--shop-name"><?php echo esc_html( $shop_name ); ?></h3>
Add hyperlink here also same as above code.

2022-06-27 02:36 UTC, digitalchild approved these changes

2022-07-18 03:52 UTC, merged